import { Inter } from "next/font/google";
import SideBar from "./_components/SideBar";
import "./globals.css";
import StoreProvider from "./StoreProvider";
// import { PersistGate } from "redux-persist/integration/react";
// import { persistor } from "./_store/store";
// import { PersistGate } from "redux-persist/es/integration/react";
// import { PersistGate } from "redux-persist/integration/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Note Keeping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-row z-10`}>
        <StoreProvider>
          {/* <PersistGate  persistor={persistor}> */}
          <div className=" md:w-[200px] h-full z-20">
            <SideBar />
            <p></p>
          </div>
          <main className="h-screen w-full md:w-[calc(100%-200px)] z-10">
            {children}</main>
          {/* </PersistGate> */}
        </StoreProvider>
      </body>
    </html>
  );
}
