import { Inter } from "next/font/google";
import SideBar from "./_components/SideBar";
import './globals.css';
import StoreProvider from "./StoreProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Note Keeping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StoreProvider>
      <body className={`${inter.className} flex flex-row`}>
        <div className="w-1/6 h-screen">
          <SideBar />
          <p></p>
        </div>
        <main className="h-screen w-[83.4%]">{children}</main>{" "}
      </body>
      </ StoreProvider>
    </html>
  );
}
